name: Check Defold Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check version
        run: |
          curl -sSL http://d.defold.com/stable/info.json -o latest_info.json
          latest_version=$(jq -r .version latest_info.json)
          echo "::set-output name=latest_version::$latest_version"
          if [ -f "info.json" ]; then
            current_version=$(jq -r .version info.json)
          else
            current_version=""
          fi
          echo "Current version: $current_version"
          echo "Latest version: $latest_version"
          if [ "$current_version" != "$latest_version" ]; then
            echo "Version changed."
            version_changed=true
            echo "::set-output name=version_changed::false"
          else
            echo "Version unchanged."
            version_changed=false
            echo "::set-output name=version_changed::false"
          fi
          echo "Version check: ${{ steps.vars.outputs.latest_version }}"
          
      - name: Commit
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.vars.outputs.version_changed == true }}
        with:
          message: "Update version to ${{ steps.vars.outputs.latest_version }}"
          add: info.json
          fetch: true
          push: true
          tag: 'v${{ steps.vars.outputs.latest_version }} --force'

      - name: Build container image
        uses: ./.github/workflows/docker-publish.yml
        if: ${{ steps.vars.outputs.version_changed == true }}
