name: Check Defold updates

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest version
        run: |
          curl -sSL http://d.defold.com/stable/info.json -o latest_info.json
          latest_version=$(jq -r .version latest_info.json)

      - name: Compare versions
        run: |
          PREVIOUS_VERSION=$(jq -r .version info.json)
          LATEST_VERSION=${{ steps.vars.outputs.latest_version }}
          if [ "$PREVIOUS_VERSION" != "$LATEST_VERSION" ]; then
            echo "Version changed. Updating repository."
            echo "version_changed::true"
          else
            echo "Version unchanged. No action needed."
            echo "version_changed::false"
          fi
          
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        if: ${{ needs.vars.outputs.version_changed == 'true' }}
        with:
          message: "Update version to ${{ steps.vars.outputs.latest_version }}"
          add: info.json
          fetch: true
          push: true
          tag: 'v${{ steps.check-version.outputs.latest_version }} --force'
          
