name: Docker

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: docker.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge with sigstore when running outside of PRs
      id-token: write

    steps:
      - name: Get repository name lowercase
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool to sign and verify container images
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.3.0

      # Set up BuildKit Docker container builder
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        env:
          VERSION: $(jq -r .version info.json)
          TAGS: ${{ env.IMAGE_NAME }}:latest,v${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        env:
          #TAGS: ${{ env.IMAGE_NAME }}:latest,v${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
