name: Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Get repository name lowercase
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        env:
          TAGS: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:v${{ $(jq -r .version info.json) }}
        run: |
          echo "TAGS: ${TAGS}"
